export const Action = { FILTER_DATE: 'FILTER_DATE', FILTER_RESERVED:'FILTER_RESERVED',FILTER_ADULT: 'FILTER_ADULTS', FILTER_CHILDREN: 'FILTER_CHILDREN' };

export const Mutations = { SET_ROOMS: 'setRooms'};