export const Action = { FILTER_DATE: 'FILTER_DATE', FILTER_RESERVED:'FILTER_RESERVED', ADD_BOOKROOM:'ADD_BOOKROOM', CLEAR_BOOKROOM:'CLEAR_BOOKROOM', LIST_RESERVES:'LIST_RESERVES'};

export const Mutations = { SET_ROOMS: 'setRooms', SET_RESERVES:'setReserves', SET_BOOKROOM:'setBookRoom', DELETE_BOOKROOM:'deleteBookRoom'};